//! Storage schema migration from v1 to v2 for `Balance`.
//!
//! Generated by `soroban-migrate generate`. Do not edit: the next run
//! overwrites it. Change the schemas or the plan and regenerate with
//!
//! ```text
//! soroban-migrate generate 1 2
//! ```
//!
//! # Idempotency
//!
//! Every assignment below is guarded so that visiting an entry twice is a no-op.

#[allow(unused_imports)]
use soroban_migrate::migration::{EntryOutcome, Migration};
#[allow(unused_imports)]
use soroban_migrate::MigrationError;
#[allow(unused_imports)]
use soroban_sdk::*;
#[allow(unused_imports)]
use crate::schema::*;

/// Moves `Balance` from the v1 shape to the v2 shape.
#[allow(dead_code)]
pub struct BalanceV1ToV2;

impl Migration for BalanceV1ToV2 {
    type Keys = crate::keys::DataKey;
    const FROM: u32 = 1;
    const TO: u32 = 2;

    fn up(env: &Env, key: &Val) -> Result<EntryOutcome, MigrationError> {
        let storage = env.storage().persistent();
        if !storage.has::<Val>(key) {
            return Ok(EntryOutcome::Skipped);
        }
        // This migration rewrites no field. It still has to run: `executor::batch`
        // records every visited key under the new version's index and advances the
        // schema version once the cursor reaches the end, so running it is what makes
        // the new version the contract's declared shape. The change itself is absorbed
        // by tolerant decoding: an entry written before it arrives with the new field
        // as `None`, which is what lets the upgrade ship before the migration finishes.
        Ok(EntryOutcome::AlreadyCurrent)
    }
}
